### PR TITLE
Some updates to build on latest macOS

### PR DESCRIPTION
**Pull request by razum2um**
- [x] ignore binaries (I suggest to push them into releases)
- [x] currently build is failing because latest macOS is no longer shipped with stdlibc

```
+ xcrun -sdk macosx g++ -mmacosx-version-min=10.8 -arch i386 -arch x86_64 -I. -c -std=c++11 -o ldid.o ldid.cpp
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
ldid.cpp:30:10: fatal error: 'cstring' file not found
#include <cstring>
         ^~~~~~~~~
1 warning and 1 error generated.
```

### CODE REVIEW

**Comment by xerub** [comment]
You're right the binaries should be in releases. I'll see to it when I have some time.
About the x86 (32bit) I'm not ready to let it go just yet :)

**Comment by trufae** [comment]
Damn, i was about to push the same PR now 🙈 can we merge this now? or add a make target to build on old targets (or enable the i386 slice to be added depending on the version of xcode)

**Comment by xerub** [comment]
@trufae I like the idea of keeping old targets, at least for a while. Do you have a PR?

**Comment by trufae** [comment]
I have no PR ready, so, all yours whenever you have some time

**Comment by xerub** [comment]
I merged it. Will fix the i386 build later :)

**Pull request merged**
